/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShopTeaser {
        "image": string;
    }
}
declare global {
    interface HTMLShopTeaserElement extends Components.ShopTeaser, HTMLStencilElement {
    }
    var HTMLShopTeaserElement: {
        prototype: HTMLShopTeaserElement;
        new (): HTMLShopTeaserElement;
    };
    interface HTMLElementTagNameMap {
        "shop-teaser": HTMLShopTeaserElement;
    }
}
declare namespace LocalJSX {
    interface ShopTeaser {
        "image"?: string;
    }
    interface IntrinsicElements {
        "shop-teaser": ShopTeaser;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shop-teaser": LocalJSX.ShopTeaser & JSXBase.HTMLAttributes<HTMLShopTeaserElement>;
        }
    }
}
