/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShopArticleteaser {
    }
    interface ShopPopup {
        "image": string;
        "test": () => Promise<void>;
    }
}
declare global {
    interface HTMLShopArticleteaserElement extends Components.ShopArticleteaser, HTMLStencilElement {
    }
    var HTMLShopArticleteaserElement: {
        prototype: HTMLShopArticleteaserElement;
        new (): HTMLShopArticleteaserElement;
    };
    interface HTMLShopPopupElement extends Components.ShopPopup, HTMLStencilElement {
    }
    var HTMLShopPopupElement: {
        prototype: HTMLShopPopupElement;
        new (): HTMLShopPopupElement;
    };
    interface HTMLElementTagNameMap {
        "shop-articleteaser": HTMLShopArticleteaserElement;
        "shop-popup": HTMLShopPopupElement;
    }
}
declare namespace LocalJSX {
    interface ShopArticleteaser {
    }
    interface ShopPopup {
        "image"?: string;
    }
    interface IntrinsicElements {
        "shop-articleteaser": ShopArticleteaser;
        "shop-popup": ShopPopup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shop-articleteaser": LocalJSX.ShopArticleteaser & JSXBase.HTMLAttributes<HTMLShopArticleteaserElement>;
            "shop-popup": LocalJSX.ShopPopup & JSXBase.HTMLAttributes<HTMLShopPopupElement>;
        }
    }
}
